### ISSUE TITLE
cannot import name 'set_session_id' 

### ISSUE THREAD

**Issue by 89z** [Quatrecentquatre-404/instagram-guest-api#1]
PS D:\Desktop\instagram-guest-api-main> python.exe .\tests.py
Traceback (most recent call last):
  File "D:\Desktop\instagram-guest-api-main\tests.py", line 1, in <module>
    import src as Instagram
  File "D:\Desktop\instagram-guest-api-main\src\__init__.py", line 4, in <module>
    from .core import fetch_user_stories, fetch_post_properties, fetch_queries_hash, fetch_user, fetch_user_posts, set_session_id
ImportError: cannot import name 'set_session_id' from 'src.core' (D:\Desktop\instagram-guest-api-main\src\core.py)

**Comment by Quatrecentquatre-404** [comment]
Thanks for the report, I'm going to fix it.
